import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <header className="w-full bg-white shadow-sm p-4 flex items-center justify-between">
        {/* Левый логотип */}
        <div className="text-2xl font-bold">ТМЦ</div>

        {/* Центр - навигация */}
        <nav className="flex gap-6 mx-auto">
          <Link href="/" className="hover:underline">
            Товары
          </Link>
          <Link href="/order" className="hover:underline">
            Заявки
          </Link>
          <Link href="/income" className="hover:underline">
            Поступления
          </Link>
        </nav>

        {/* Справа пока пусто */}
        <div style={{ width: "100px" }}></div>
      </header>
      {children}
      <Toaster />
      </body>
    </html>
  );
}
